export const TYPE = {
  CONTACT_LIST: 'CONTACT_LIST',
  CONTACT_LIST_SUCCESS: 'CONTACT_LIST_SUCCESS',
  CONTACT_LIST_FAIL: 'CONTACT_LIST_FAIL',
  CONTACT_DETAIL: 'CONTACT_DETAIL',
  CONTACT_DETAIL_SUCCESS: 'CONTACT_DETAIL_SUCCESS',
  CONTACT_DETAIL_FAIL: 'CONTACT_DETAIL_FAIL',
  LAST_SEEN: 'LAST_SEEN',
  LAST_SEEN_CLEAR: 'LAST_SEEN_CLEAR',
};
